from app.db.base import Base  # noqa
from app.models.usuario import Usuario  # noqa
from app.models.semestre import Semestre  # noqa
from app.models.turma import Turma  # noqa
from app.models.disciplina import Disciplina  # noqa
from app.models.professor import Professor  # noqa
from app.models.sala import Sala  # noqa
from app.models.horario import Horario  # noqa
from app.models.alocacao import AlocacaoProfessor  # noqa
from app.models.disponibilidade import DisponibilidadeProfessor  # noqa
